import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from "./page.module.css"
import NavBar from './components/navBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <main className={`${inter.className} ${styles.main}`}>
        <NavBar />
        {children}
        </main>
    
  )
}
